#!/usr/bin/env bash
# This script configures Nginx to add a custom HTTP header with the server's hostname

# Update package list and install Nginx
echo "Updating package list and installing Nginx..."
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index page
echo "This is Evander from Holberton School" | sudo tee /var/www/html/index.html

# Performing a redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.github.com\/evand3rr permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

#Creating a custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/page404.html

#Custom HTTP response header
sudo sed -i "server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Test the Nginx configuration to ensure it's valid
sudo nginx -t

# Restart nginx
sudo service nginx restart
