#!/usr/bin/env bash
# Script to install and configure HAProxy on lb-01 server

# Update system and install HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown $USER:USER /etc/haproxy/haproxy.config

echo "
frontend evand3rr
    bind *:80
    mode http
    default_backend app

backend app
    balance roundrobin
    server 6432-web-01 34.227.176.224 check
    server 6432-web-02 44.203.84.89 check" >> /etc/haproxy/haproxy.config

# Restart HAProxy service
sudo service haproxy restart
